kind: Service
apiVersion: v1
metadata:
  name: app-service-security
spec:
  type: LoadBalancer
  selector:
    app: service-security
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
    name: http